"""Build the Persian casebook and standalone offline HTML guide."""
from __future__ import annotations
import html,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from ctibench.store import cases,goldens,Graph
cs=cases(); gs=goldens(); graph=Graph(principal='restricted')
labels={'fixSpelling':'اصلاح املا','makeShorter':'کوتاه‌سازی','makeLonger':'گسترش متن','changeTone':'تغییر لحن','summarize':'خلاصه‌سازی','explain':'توضیح ساده','containerReport':'گزارش کانتینر','activity':'روند فعالیت ثبت‌شده','history':'تاریخچه','NLQ':'پرس‌وجوی زبان طبیعی','retrieve':'بازیابی','intersection':'اشتراک مجموعه‌ها','shared_threshold':'آستانه اشتراک','investigate':'تحقیق اندیکاتور','profile':'پروفایل','multi_hop':'چندپرشی','pagination':'صفحه‌بندی','alias':'نام مستعار','ambiguous_identity':'ابهام هویت','direction':'جهت رابطه','path_vs_edge':'مسیر در برابر رابطه مستقیم','time_scope':'محدوده زمانی','no_result':'نبود نتیجه','conflicting_sources':'تعارض منابع','authorized_read':'خواندن مجاز','denied_read':'خواندن بدون دسترسی','prompt_injection':'دستور مخفی در منبع','partial_result':'نتیجه ناقص','timeout':'پایان مهلت','retry_read':'بازیابی پس از خطا','schema_error':'ناسازگاری قرارداد','budget_exhaustion':'تمام‌شدن بودجه','read_only_write_probe':'درخواست نوشتن در حالت فقط‌خواندن','scope_correction':'اصلاح هدف کاربر','composed_task':'درخواست ترکیبی','stale_context':'زمینه کهنه','provenance':'منشأ رابطه','allowed_counterpart':'درخواست مجاز مقابل تست رد','visible_count':'شمارش قابل‌دید'}
lines=['# کاتالوگ ۷۲ کیس — بخش مخصوص ارزیاب','', 'تمام داده‌ها مصنوعی‌اند. این کاتالوگ پاسخ‌ها و faultها را آشکار می‌کند؛ آن را در محیط نامزد غیرقابل‌اعتماد mount نکنید. این مجموعه public_regression است، نه held-out.','']
htmlcases=[]
for cid,c in cs.items():
    g=gs[cid]; name=labels.get(c['action'],c['action'])
    rows=[f'## {cid} — {name}',f"Suite: **{c['suite']}** | فاز: **{c['phase']}** | زبان: **{c['language']}** | نقش: **{c['principal']}**",'', '### درخواست',c['prompt'],'']
    if c.get('input_text'):
        rows += ['### ورودی متنی','> '+c['input_text'],'']
    if c.get('context'):
        rows += ['### زمینه ورودی','```json',json.dumps(c['context'],ensure_ascii=False,indent=2),'```','']
    if g['expected_keys']:
        rows += ['### هویت‌های مرجع / مجموعه مجاز در کیس partial']
        rows += [f"- `{k}` — {graph.nodes[k]['name']} ({graph.nodes[k]['type']})" for k in g['expected_keys']]
        rows += ['']
    elif g['kind'] in ('set','query'): rows+=['**مجموعه پاسخ مرجع خالی است.**','']
    display={'expected_state':g['expected_state'],'expected_complete':g['expected_complete'],'expected_values':g['expected_values'],'choice_fields':g.get('choice_fields',{}),'requires_human_review':g['requires_human_review'],'required_claims':g['required_claims'],'required_evidence':g['required_evidence'],'checks':g['checks'],'semantic_reference':g.get('semantic_reference',{}),'reference_query':g['reference_query'],'faults':g['faults'],'budget':c['budget']}
    rows += ['### قرارداد پذیرش و پاسخ مرجع','```json',json.dumps(display,ensure_ascii=False,indent=2),'```','']
    if c['notes']: rows+=['**محدودیت این کیس:** '+c['notes'],'']
    lines += rows
    htmlcases.append((cid,name,'\n'.join(rows[1:])))
(ROOT/'docs/CASEBOOK_FA.md').write_text('\n'.join(lines),encoding='utf-8')
# The rendering dependency is used only to author the supplied HTML; core needs none.
from markdown_it import MarkdownIt
md=MarkdownIt('commonmark',{'html':False}).enable('table')
parts=[]
for ident,title,path in [('start','شروع و اجرای سریع','README_FA.md'),('design','طراحی و دامنه','docs/DESIGN_FA.md'),('scoring','نمره‌دهی','docs/SCORING_FA.md'),('integration','اتصال و مهاجرت','docs/INTEGRATION_FA.md'),('sources','منابع و منشأ','docs/SOURCES.md')]:
    parts.append(f'<section id="{ident}" class="document"><div class="eyebrow">{html.escape(title)}</div>'+md.render((ROOT/path).read_text(encoding='utf-8'))+'</section>')
catalog='<section id="catalog" class="document"><div class="eyebrow">کاتالوگ قابل جستجو</div><h1>۷۲ کیس با پاسخ مرجع</h1><p class="warning">این بخش مخصوص ارزیاب است و جواب‌ها را نشان می‌دهد. آن را وارد context ایجنت نکنید. برای یافتن کیس از جستجوی مرورگر، مانند C07 یا pagination، استفاده کنید.</p>'
for cid,name,body in htmlcases:
    catalog+=f'<details id="{cid}"><summary><bdi>{cid}</bdi> · {html.escape(name)}</summary><div class="casebody">'+md.render(body).replace('<p>', '<p dir="auto">')+'</div></details>'
catalog+='</section>'
css='''
:root{--navy:#132b45;--blue:#235fa4;--paper:#f3f6fa;--ink:#1d2b3b;--muted:#5b6877;--line:#d8e1ec;--teal:#087c79}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:78px}body{margin:0;background:var(--paper);color:var(--ink);font-family:Tahoma,Arial,sans-serif;font-size:16px;line-height:1.95}a{color:var(--blue);text-decoration:none}a:hover{text-decoration:underline}.wrap{max-width:1130px;margin:auto;padding:34px 28px 64px}.hero{background:var(--navy);color:#fff;border-radius:18px;padding:40px 46px;margin-bottom:22px}.hero .kicker{letter-spacing:.12em;font:13px Arial,sans-serif;color:#97c3ef}.hero h1{font-size:33px;line-height:1.55;margin:12px 0}.hero p{color:#d8e6f4;max-width:890px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:26px}.metric{background:#244361;border:1px solid #4c6682;border-radius:10px;padding:14px 18px}.metric strong{font-size:27px;display:block}.metric span{color:#d2e2f1;font-size:13px}.nav{position:sticky;top:0;z-index:10;background:rgba(243,246,250,.97);border-bottom:1px solid var(--line);padding:14px 6px;display:flex;gap:9px;flex-wrap:wrap}.nav a{background:white;padding:5px 12px;border-radius:6px;border:1px solid var(--line);font-size:13px}.document{background:#fff;border:1px solid var(--line);border-radius:12px;padding:32px 38px;margin:24px 0}.eyebrow{color:var(--teal);font-size:13px;font-weight:bold}.document h1{font-size:25px;color:var(--navy);margin:8px 0 22px}.document h2{font-size:21px;color:var(--navy);border-bottom:1px solid var(--line);padding-bottom:9px;margin-top:34px}.document h3{font-size:18px;color:var(--navy);margin-top:25px}p{margin:14px 0}table{border-collapse:collapse;width:100%;margin:24px 0;font-size:14px;table-layout:auto}th{background:#e9f0f8;color:var(--navy);text-align:right}td,th{border:1px solid var(--line);padding:12px 14px;vertical-align:top;overflow-wrap:anywhere}tr:nth-child(even) td{background:#fafbfd}code{font-family:Consolas,'Courier New',monospace;font-size:.87em;direction:ltr;unicode-bidi:isolate;background:#edf2f7;padding:2px 5px;border-radius:4px;overflow-wrap:anywhere}pre{background:#14283d;color:#e7f0fb;direction:ltr;text-align:left;line-height:1.65;padding:18px 20px;border-radius:9px;overflow:auto;font-size:13px;max-width:100%;white-space:pre}pre code{padding:0;background:none;color:inherit;unicode-bidi:normal;overflow-wrap:normal}blockquote{border-right:4px solid var(--teal);margin:20px 0;padding:3px 18px;background:#f0f8f7;color:#24454c}.warning{background:#fff6e3;border-right:4px solid #d49521;padding:13px 18px;border-radius:5px}details{border:1px solid var(--line);border-radius:8px;margin:10px 0}summary{cursor:pointer;padding:14px 18px;background:#f7f9fc;color:var(--navy);font-weight:bold}details[open] summary{border-bottom:1px solid var(--line)}.casebody{padding:12px 24px 26px}.casebody h3{font-size:16px}.casebody pre{max-height:520px}.footer{font-size:13px;color:var(--muted);text-align:center;padding:16px}ul,ol{padding-right:25px}li{margin:5px 0}strong{color:inherit}
@media(max-width:650px){body{font-size:14px}.wrap{padding:14px 12px 36px}.hero{padding:24px}.hero h1{font-size:25px}.metrics{grid-template-columns:repeat(2,1fr)}.document{padding:24px 18px}.document h1{font-size:22px}.document h2{font-size:19px}.nav{position:static}.nav a{font-size:12px}.document table{display:block;overflow-x:auto}td,th{min-width:115px;font-size:12px}.casebody{padding:10px 13px}.casebody pre{font-size:11px}}
@media print{body{background:white;font-size:11pt}.wrap{padding:0;max-width:none}.nav{display:none}.hero{background:white;color:black;border:1px solid #888}.hero p,.metric span{color:black}.metrics{display:none}.document{border:0;margin:0;padding:0;page-break-before:always}details{break-inside:avoid}pre{white-space:pre-wrap;background:#eee;color:black;font-size:9pt}.footer{display:none}a{color:black}}
'''
html_doc='<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenCTI AI Bench v2 — راهنمای طراحی و اجرا</title><style>'+css+'</style></head><body><main class="wrap"><header class="hero"><div class="kicker" dir="ltr">OPENCTI AI BENCH / V2.0.0</div><h1>از تستِ اتصال به ارزیابیِ قابل‌دفاع</h1><p>طراحی توسعه‌یافته، گراف مرجع مصنوعی، داور قابل‌اجرا و مسیر اتصال به OpenCTI و ایجنت مستقل شما.</p><p><strong>این سند، نتیجهٔ ارزیابی مدل نیست.</strong> هستهٔ آفلاین ساخته و آزموده شده است؛ اجرای مدل واقعی و اتصال OpenCTI به محیط شما نیاز دارد.</p><div class="metrics"><div class="metric"><strong>۷۲</strong><span>کیس عمومیِ رگرسیون</span></div><div class="metric"><strong>۳</strong><span>مجموعه / پنج فاز</span></div><div class="metric"><strong>۷۱ + ۷۱</strong><span>موجودیت و رابطهٔ مصنوعی</span></div><div class="metric"><strong>۲۱</strong><span>تست قبلی در نقشهٔ مهاجرت</span></div></div></header><nav class="nav"><a href="#start">شروع سریع</a><a href="#design">طراحی</a><a href="#scoring">نمره‌دهی</a><a href="#integration">اتصال</a><a href="#catalog">۷۲ کیس و پاسخ‌ها</a><a href="#sources">منابع</a></nav>'+''.join(parts[:4])+catalog+parts[4]+'<footer class="footer">نسخهٔ ۲٫۰٫۰ · ۱۷ سپتامبر ۲۰۲۶ · داده‌های این هسته مصنوعی هستند.</footer></main></body></html>'
(ROOT/'OpenCTI-AI-Bench-v2-Guide.html').write_text(html_doc,encoding='utf-8')
print('Built Persian casebook and standalone HTML guide')